- name: Generate image on the USB storage
  hosts: all
  become: yes
  tasks:
  - name: Cleanup user files for sanity
    shell:
      cmd: "rm -rvf /home/pi/.bash_history /home/pi/.witnessangel /home/pi/.local/share/Trash/*"
  - name: Remove configured wifi network if any
    shell:
      cmd: wpa_cli remove_network 0 && wpa_cli save_config # This still returns 0 on failure, weirdly
  - name: Remove useless packages from the apt cache
    apt:
      autoclean: yes  # Might be redundant with pishrink's own cleanup, but it's OK
  - name: Cleanup system files to make the image generic (this resets SSH hostkey!)
    shell:
      cmd: "rm -rvf /var/cache/apt/archives/* /var/lib/dhcpcd/*.lease var/log/* /var/tmp/* /tmp/* /etc/ssh/*_host_*"
  - name: Download pishrink utility in advance
    shell:
      cmd: wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
      chdir: /var/tmp/
      creates: /var/tmp/pishrink.sh
  - name: Dump raw sdcard image to usb key
    shell:
      cmd: dd if=/dev/mmcblk0 of=/media/pi/BigKey/raspberrypi_warecorder.img bs=1M
  - name: Build cleaned-up and shrinked image from raw sdcard image (NOT gzipped)
    shell:
      # No need for option "-p", cleanup already done
      cmd: bash /var/tmp/pishrink.sh -av /media/pi/BigKey/raspberrypi_warecorder.img


